/* Automatically generated by './build/bin/build-entry.js' */
import GkAdvancedPermissions from '../packages/advanced-permissions/index.js';
import GkBreadcrumb from '../packages/breadcrumb/index.js';
import GkButton from '../packages/button/index.js';
import GkCheckbox from '../packages/checkbox/index.js';
import GkDropdown from '../packages/dropdown/index.js';
import GkFileicon from '../packages/fileicon/index.js';
import GkFinder from '../packages/finder/index.js';
// import Loading from '../packages/loading/index.js';
import GkMenu from '../packages/menu/index.js';
import GkPermissions from '../packages/permissions/index.js';
// import ScrollLoad from '../packages/scroll-load/index.js';
import GkSlide from '../packages/slide/index.js';
import GkTable from '../packages/table/index.js';
import GkThumbnail from '../packages/thumbnail/index.js';
import GkTooltip from '../packages/tooltip/index.js';
import GkUploader from '../packages/uploader/index.js';

module.exports = {
  version: '1.0.0',
  GkBreadcrumb,
  GkButton,
  GkCheckbox,
  GkDropdown,
  GkFileicon,
  GkFinder,
  GkMenu,
  GkSlide,
  GkTable,
  GkThumbnail,
  GkTooltip,
  GkUploader,
  GkPermissions,
  GkAdvancedPermissions
};
module.exports.default = module.exports;
